/* RELATORIO GERAL DE TODOS OS CLIENTES */
DESC CLIENTE;
DESC ENDERECO;
DESC TELEFONE;

SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.SEXO, CLIENTE.EMAIL, CLIENTE.CPF, 
       ENDERECO.RUA, ENDERECO.BAIRRO, ENDERECO.CIDADE, ENDERECO.ESTADO, 
       TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;


--- FILTRAR VARIOS IDS**
SELECT * FROM CLIENTE
WHERE IDCLIENTE IN (1, 2, 3, 4, 5);

--- ATUALIZAR VARIOS IDS**
UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE IN (1, 2, 3, 4);

--- DELETAR VÁRIOS IDS**
DELETE FROM CLIENTE 
WHERE IDCLIENTE IN (1, 2, 3, 4, 5);



/* RELATORIO GERAL DE TODOS OS CLIENTES (TELEFONE E ENDERECO) */

SELECT * FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE 
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;


/* RELATORIO DE HOMENS */

SELECT * FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE 
ON TELEFONE.ID_CLIENTE = CLIENTE.IDCLIENTE
WHERE SEXO = 'M';


/* RELATORIO DE MULHERES */

SELECT * FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE 
ON TELEFONE.ID_CLIENTE = CLIENTE.IDCLIENTE
WHERE SEXO = 'F';



/* QUANTIDADE DE HOMENS E MULHERES */

SELECT COUNT(*), SEXO FROM CLIENTE
GROUP BY SEXO;

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NAO TENHAM CELULAR */




/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATÓRIO COM O NOME,
EMAIL E TELEFONE CELULAR
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT CLIENTE.NOME, CLIENTE.EMAIL, TELEFONE.NUMERO AS CELULAR
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR
DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT CLIENTE.NOME, CLIENTE.EMAIL, TELEFONE.NUMERO AS CELULAR
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'F'
AND ESTADO = 'SP';


