CREATE TABLE CLIENTE (
    IDCLIENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO TEXT NOT NULL CHECK(SEXO IN('M','F')),
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
    IDIENDERECO INTEGER PRIMARY KEY AUTOINCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE
);

CREATE TABLE TELEFONE (
    IDTELEFONE INTEGER PRIMARY KEY AUTOINCREMENT,
    TIPO TEXT NOT NULL CHECK(TIPO IN('RES', 'COM', 'CEL')),
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);