CREATE DATABASE AlugaCarBrasil;

USE AlugaCarBrasil;

CREATE TABLE Cliente(
		 CNH VARCHAR(11) PRIMARY KEY NOT NULL,
		 Nome_Cliente VARCHAR(50),
		 Telefone_Cliente VARCHAR(20)
);

CREATE TABLE Modelo(
		IDModelo INT PRIMARY KEY AUTO_INCREMENT,
		Nome_Modelo VARCHAR(50)
);

CREATE TABLE Categoria(
		IDCategoria INT PRIMARY KEY AUTO_INCREMENT,
		Categoria_nome VARCHAR(50)		
);

CREATE TABLE Situacao(
		IDStatus INT PRIMARY KEY AUTO_INCREMENT,
		Status_Nome VARCHAR(50)
);

CREATE TABLE Carro(
		Placa_Carro VARCHAR(7) PRIMARY KEY NOT NULL,
		Ano YEAR,
		ModeloID INT,
		CategoriaID INT,
		StatusID INT,
CONSTRAINT FK_CARRO_MODELO FOREIGN KEY(ModeloID) REFERENCES Modelo(IDModelo),
CONSTRAINT FK_CARRO_CATEGORIA FOREIGN KEY(CategoriaID) REFERENCES Categoria(IDCategoria),
CONSTRAINT FK_CARRO_STATUS FOREIGN KEY(StatusID) REFERENCES Situacao(IDStatus)
);


CREATE TABLE Aluguel(
		AluguelID INT PRIMARY KEY AUTO_INCREMENT,
		CNH VARCHAR(11),
		Placa_Carro VARCHAR(7),
		Data_Inicio DATE NOT NULL,
		Data_Dev DATE,
		Valor_Aluguel DECIMAL(10,2),
		CONSTRAINT FK_ALUGUEL_CNH FOREIGN KEY (CNH) REFERENCES Cliente(CNH),
		CONSTRAINT FK_ALUGUEL_CARRO FOREIGN KEY (Placa_Carro) REFERENCES Carro(Placa_Carro)
);
